runtime: go
api_version: go1

handlers:
- url: /
  static_files: ../frontend/dist/index.html
  upload: ../frontend/dist/index.html

- url: /
  static_dir: ../frontend/dist/

- url: /api/.*
  script: api.go
